version: "3.7"

networks:
    genesis:

services:
    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginx-genesis
        environment:
            TZ: Europe/Kiev
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./Docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php
        networks:
            - genesis
        extra_hosts:
            - "host.docker.internal:host-gateway"

    php:
        build:
            context: Docker/dockerfiles
            dockerfile: php8.1-fpm-Dockerfile
        container_name: php81-genesis
        environment:
            TZ: Europe/Kiev
        volumes:
            - ./:/var/www
#            - ./docker/php/php.ini:/usr/local/etc/php-fpm.d/40-custom.ini
        ports:
            - "9001:9000"
        networks:
            - genesis
        extra_hosts:
            - "host.docker.internal:host-gateway"

    composer:
        build:
            context: Docker/dockerfiles
            dockerfile: php8.1-cli-composer-Dockerfile
        container_name: composer-genesis
        volumes:
            - ./:/var/www
        environment:
            TZ: Europe/Kiev
        working_dir: /var/www/
        entrypoint: [ "composer" ]
        depends_on:
            - php
        networks:
            - genesis

    artisan:
        build:
            context: Docker/dockerfiles
            dockerfile: php8.1-cli-composer-Dockerfile
        container_name: artisan-genesis
        environment:
            TZ: Europe/Kiev
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: [ "php", "/var/www/artisan" ]
        networks:
            - genesis
